### ISSUE TITLE
Platforms/binaries cause errors

### ISSUE THREAD

**Issue by maxscheurer** [ryanmcgreevy/ModelMaker#13]
Pre-compiled Rosetta versions seem to have
the prefix `static` in the binary files, i.e.
`rosetta_scripts.static.linuxgccrelease`. If no binary without this prefix is available, Rosetta
cannot be executed.

**Comment by ryanmcgreevy** [comment]
The fix for this in your [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/a92313ce96d14a276442307bf604f6177af29499) should work for now, but I had backed out a similar change a while back because it caused issues for certain commands (at least on my Mac). I will investigate this issue further and see if this is good enough (and if we can have a similar fix on OSX) or whether we need a different fix.

**Comment by trudack** [comment]
Does your comment mean that in principle the newest version should also work for me?

In the version I just update I still have to change line 19 in modelmaker.tcl to static.linuxgccrelease

**Comment by maxscheurer** [comment]
I reverted the fix Ryan mentioned before, as it was causing problems. As you said, you have to change your rosettaEXE to `static.linuxgccrelease`

**Comment by ryanmcgreevy** [comment]
I am looking into a more permanent and universal fix to this issue and will update everyone when it is implemented.

**Comment by ryanmcgreevy** [comment]
@trudack does your Rosetta _only_ have `static.whatever` binaries or does it also have `default.whatever` binaries. My installation has all three (no prefix, static, and default). If `default` exists on every installation, then we can just hard code that in, along with a wildcard for the compiler (this is what I've done in this [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/02f9a9e9b7703934c0bf1708bf46db157aebfade) which also contains a fix for the bug caused when using wildcards and rosetta clustering, so wildcards should be okay now).

**Comment by trudack** [comment]
If you do not compile anything it only has static.

For example on our cluster here we have issue to compile it because it is too old.

**Comment by ryanmcgreevy** [comment]
Okay, so in this [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/43373d4b294fcd30372876fac46bd11f4be07338) I changed the default rosettaEXE to `static` which it looks like all distributions should have by default. To make it easier for the user to change this if for whatever reason they don't have that binary, or they want to specifically use some other binary (I don't know _why_ this would be the case, but options are always good), I have created a new `env(ROSETTAEXE)` environment variable that can be set in the .vmdrc just like the `ROSETTAPATH` and `ROSETTADB`. This way, the user doesn't have to change the code (but the default _should_ now work for everyone...)

**Comment by trudack** [comment]
Sorry for being annoying but unfortunately this does not solve the problem.

Issue 1: If I run full_length_model it does not recognize the '*' so in my case I have to hard code gcc and it works.

Issue 2: If you compile it and do not add the flag to also have the static version (which is not default) you do not have the static binaries

I would suggest to let the user define the compiler and the prefix static, default, ... for example in the .vmdrc ?

**Comment by ryanmcgreevy** [comment]
1. In [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/5a7847dac9a99b043bd2fd7cf8d1859d10b59128) I just made, I fixed the problem with `full_length_model`. It was the same problem I fixed with the clustering, but forgot that the same applies to that command as well. (The `*` wildcard expands just fine when .sh scripts are generated, but other commands, like `full_length_model` or the rosetta clustering, are called directly and need special tcl).

2. I guess I have to look into this further. My Rosetta, which I believe I compiled with default settings, has `static`, `default`, and 'normal' binary versions and I didn't do anything special. One of these prefixes (or the no prefix one) must be the most common form, which is what should be our default.

As for letting the user set it in the .vmdrc, please look at my previous comment. I already added in a new environment variable to do just that. I'll keep this issue open until the default prefix is decided.
