### ISSUE TITLE
modelmaker refine

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#19]
If I run the refine command from the Readme file I get this error message:

error copying "rpn11_model_5_2594_density.mrc": no such file or directory

We made the script that it can either have an dx or mrc as input. If it is an dx file it automatically converts it into an mrc file. If I remember correctly rosetta wants mrc and of course MDFF needs the dx file. The command should work with both file formats mrc and dx.

**Comment by ryanmcgreevy** [comment]
Sorry, @maxscheurer and I already discussed this but I forgot to update the README. In [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/5a7847dac9a99b043bd2fd7cf8d1859d10b59128) I just made, the README should now correctly show an .mrc file being used. The reason for requiring an .mrc input instead of .dx and using the conversion script, is because the conversion script relies on situs, which we want to avoid. Not only do we want to limit our use of 3rd party software if it's not necessary, but also situs has many problems on Macs and is a common problem in our workshops. Since VMD can easily convert .mrc to .dx, .mrc is being used as the input format.

**Comment by trudack** [comment]
OK but it still does not work for me even if I use a .mrc as input I get the error to copy the mrc file:

{"Span" 274 284 1 1 }
finished finding selections.
Rosetta started
{"Chain" 1 0 0} {"Span" 274 284 1 1 }
error copying ".mrc": no such file or directory

Looks like it does not recognize the specified name after the -density flag as now it wants to copy .mrc. If I copyrpn11_model_5_2594_density.mrc to just .mrc it works.

Also Rosetta never started even though the logfile states it. The run folder only contains rpn11_refine.sh

**Comment by ryanmcgreevy** [comment]
In [this commit](https://github.com/ryanmcgreevy/ModelMaker/commit/5a8fcef112b09356993a27c210a7dfa8a1588bd9) I fixed a bug in `refine` that was still parsing density file input as .dx. I have tested it with the tutorial example and it appears to work again. @trudack please test and close this issue if it works.
