### ISSUE TITLE
Error with makepsf

### ISSUE THREAD

**Issue by trudack** [ryanmcgreevy/ModelMaker#39]
Recently I get several times the following error if I run makepsf:

Line too short in psf file: 
   27674 RT6

couldn't read atom 27673

However if I use my old make_psf.tcl script it works. I have the feeling this only happens with files that come out of modeller or if I used the renumber.tcl script. I sent an case example to @ryanmcgreevy  by mail.

**Comment by ryanmcgreevy** [comment]
It looks like the issue is in your old script, you are reading the chain info from a .txt file. The new version takes it from the ch_seg option, and if you don't have that, it automatically takes it from the input pdb. If I switch the new version to read your .txt file, it works. I'm looking into why this is the case.

**Comment by ryanmcgreevy** [comment]
So I'm not yet sure why taking the chains and segnames from the input pdb isn't working, but in this [commit](https://github.com/ryanmcgreevy/ModelMaker/commit/98f579a5c63ebd969a1500472ad0ebe305ab8efc) I changed the chseg option of both `makepsf` and `mdff` to read from an input file instead of a list of lists. This makes it much easier to give ModelMaker the chains and segnames for a larger structure. In practice, this means in your example that gave an error, you can now use the `-chseg s4_chains.txt` option and it should work correctly now.

**Comment by trudack** [comment]
Looks good, however if the last line of the txt file is empty, it gives an syntax error. Can you catch this error and give an error message that the last line of text file should not be an empty line.

**Comment by trudack** [comment]
If I use the "mdff" module I get also syntax error. I assume that it uses still the old make psf version and probably just needs the same fix or also the option -chseg for the mdff command.

**Comment by ryanmcgreevy** [comment]
I'll fix the empty last line issue, thanks. However the commit that fixed makepsf should also already contain the same fix for `mdff` and the `-chseg` option.
